// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ar0i7Yt5By-aDAqeHmVebOp2zhbAjNs',
    appId: '1:690779818548:web:b8ce891ce43ebd507ed861',
    messagingSenderId: '690779818548',
    projectId: 'project-4f636',
    authDomain: 'project-4f636.firebaseapp.com',
    storageBucket: 'project-4f636.firebasestorage.app',
    measurementId: 'G-JWGGT0T86M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tqJbkkl3iA-c4-m0Uj1VvNc4dsrX1ds',
    appId: '1:690779818548:android:f5f54df04ee922d27ed861',
    messagingSenderId: '690779818548',
    projectId: 'project-4f636',
    storageBucket: 'project-4f636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29FZ988nbODocoEw_JkbNMAofYqZaGkY',
    appId: '1:690779818548:ios:a1b0c18cf9906dbd7ed861',
    messagingSenderId: '690779818548',
    projectId: 'project-4f636',
    storageBucket: 'project-4f636.firebasestorage.app',
    iosBundleId: 'com.example.mtproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4ar0i7Yt5By-aDAqeHmVebOp2zhbAjNs',
    appId: '1:690779818548:web:3970797beb6108c77ed861',
    messagingSenderId: '690779818548',
    projectId: 'project-4f636',
    authDomain: 'project-4f636.firebaseapp.com',
    storageBucket: 'project-4f636.firebasestorage.app',
    measurementId: 'G-J6SLHW8HK1',
  );
}
